name: kazoo-configs-bigcouch
base_branch: origin/master
exposure: private
base_core: null
template: spec.tmpl
package:
  centos7:
    name: kazoo-configs-bigcouch
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: Kazoo specific configuration for BigCouch
    description: |
      A clustered version of CouchDB, BigCouch provides the
      persistent data store service for the Kazoo platform.
      This package contains the base configuration for the
      service. If you need help you can contact us via the
      dev mailing list or on IRC at #2600hz on FreeNode.
    dist: .el7.centos
    requires:
      sudo: {}
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      mkdir -p %{buildroot}/etc/kazoo
      cp -r bigcouch %{buildroot}/etc/kazoo
      cp CHANGELOG VERSION %{buildroot}/etc/kazoo/bigcouch

      mkdir -p %{buildroot}/usr/sbin
      cp -r  system/sbin/* %{buildroot}/usr/sbin
      chmod +x %{buildroot}/usr/sbin/*

      mkdir -p %{buildroot}/etc/logrotate.d
      cp -r  system/logrotate.d/*.conf %{buildroot}/etc/logrotate.d

      mkdir -p %{buildroot}/etc/security/limits.d
      cp -r  system/security/limits.d/*.conf %{buildroot}/etc/security/limits.d

      mkdir -p %{buildroot}/usr/lib/systemd/system
      cp system/systemd/* %{buildroot}/usr/lib/systemd/system
    files:
      doc:
        - CHANGELOG
        - VERSION
      config:
        - mode: noreplace
          path: /etc/kazoo/bigcouch
        - mode: noreplace
          path: /etc/logrotate.d/*bigcouch*
        - mode: noreplace
          path: /etc/security/limits.d/*bigcouch*
      path:
        - /usr/sbin/kazoo-bigcouch
        - /usr/lib/systemd/system/kazoo-bigcouch.service
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
metapackage:
  -
    name: meta-kazoo-bigcouch
    package: kazoo-configs-bigcouch
    type: required
    branch: 'master'
